import type { ForumViewLabels, MarkdownEditorLabels } from './types';

/** Textes par défaut affichés par le ForumView. */
export const defaultForumViewLabels: ForumViewLabels = {
  loading: 'Chargement des sujets…',
  retry: 'Réessayer',
  empty: "Aucun sujet dans ce forum pour l'instant.",
  sortGroup: 'Trier les sujets',
  sortTop: 'Populaires',
  sortRecent: 'Récents',
  newThread: 'Nouveau sujet',
  voteUp: 'Voter pour',
  voteDown: 'Voter contre',
  ownVoteTitle: 'Vous ne pouvez pas voter sur votre propre publication',
  reply: 'Répondre',
  edit: 'Modifier',
  delete: 'Supprimer',
  collapseReplies: 'Replier les réponses',
  expandReplies: 'Déplier les réponses',
  collapseThread: 'Replier le fil',
  replyOne: 'réponse',
  replyMany: 'réponses',
  noReplies: 'Aucune réponse',
  pinned: 'Épinglé',
  deleteTitle: 'Supprimer le message',
  deleteContent: 'Ce message et ses réponses seront définitivement supprimés. Continuer ?',
  newThreadTitle: 'Titre du sujet',
  publish: 'Publier',
  editSave: 'Enregistrer',
  editPlaceholder: 'Modifier le message…',
  replyPlaceholder: 'Votre réponse…',
  newThreadPlaceholder: 'Rédige ton sujet…',
};

/** Textes par défaut internes du MarkdownEditor. */
export const defaultMarkdownEditorLabels: MarkdownEditorLabels = {
  toolbar: 'Mise en forme Markdown',
  heading: 'Titre',
  headingMenu: 'Niveau de titre',
  headingTitle: 'Titre',
  headingSub: 'Sous-titre',
  headingSubSub: 'En-tête',
  headingSmall: 'Petite en-tête',
  bold: 'Gras',
  italic: 'Italique',
  inlineCode: 'Code en ligne',
  codeBlock: 'Bloc de code',
  codeBlockMenu: 'Langage du bloc de code',
  noLanguage: 'Sans langage',
  link: 'Lien',
  bulletList: 'Liste à puces',
  numberedList: 'Liste numérotée',
  quote: 'Citation',
  preview: 'Aperçu',
  previewExit: 'Modifier',
  cancel: 'Annuler',
  emptyPreview: 'Rien à prévisualiser.',
};
