spring.application.name=gateway

spring.config.import=optional:file:../.env[.properties]

server.port=${GATEWAY_PORT:8080}

spring.cloud.gateway.server.webmvc.routes[0].id=core-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://${CORE_SERVICE_HOST:localhost}:${CORE_SERVICE_PORT:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/**

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:8083}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webmvc.routes[2].id=mcp-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://${MCP_SERVICE_HOST:localhost}:${MCP_SERVICE_PORT:8082}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/mcp/**

%dev.logging.level.com.moodit.gateway=DEBUG
%prod.logging.level.com.moodit.gateway=INFO