-- Schéma H2 pour les tests JPA de suppression de programme.
-- Reproduit les tables et les contraintes ON DELETE CASCADE de init.sql qui portent la
-- logique testée (nettoyage des cours orphelins + cascades program_course / User_Program_Role).
-- Volontairement RÉDUIT aux tables touchées par ProgramService.deleteProgram.

CREATE TABLE establishment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  domain_email VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE program (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  code VARCHAR(128) NOT NULL,
  cohort VARCHAR(128) NOT NULL,
  color VARCHAR(9) NOT NULL DEFAULT '#0a5cc0',
  establishment_id INT NOT NULL,
  CONSTRAINT fk_program_establishment FOREIGN KEY (establishment_id)
    REFERENCES establishment(id) ON DELETE CASCADE
);

CREATE TABLE course (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(128),
  code VARCHAR(128) NOT NULL
);

CREATE TABLE program_course (
  program_id INT NOT NULL,
  course_id INT NOT NULL,
  PRIMARY KEY (program_id, course_id),
  CONSTRAINT fk_pc_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_pc_course FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
);

CREATE TABLE user_ (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  first_name VARCHAR(128) NOT NULL,
  last_name VARCHAR(128) NOT NULL,
  email VARCHAR(256) NOT NULL UNIQUE,
  settings TEXT,
  avatar_color VARCHAR(9),
  active_token_hash VARCHAR(256),
  password_hash VARCHAR(256) NOT NULL,
  created_at TIMESTAMP
);

CREATE TABLE role (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  program_assignable BOOLEAN NOT NULL DEFAULT TRUE,
  global_assignable BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE user_program (
  program_id INT NOT NULL,
  user_id INT NOT NULL,
  PRIMARY KEY (program_id, user_id),
  CONSTRAINT fk_up_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_up_user FOREIGN KEY (user_id) REFERENCES user_(id) ON DELETE CASCADE
);

CREATE TABLE user_program_role (
  program_id INT NOT NULL,
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  PRIMARY KEY (program_id, user_id, role_id),
  CONSTRAINT fk_upr_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_upr_user FOREIGN KEY (user_id) REFERENCES user_(id) ON DELETE CASCADE,
  CONSTRAINT fk_upr_role FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
);

CREATE TABLE enrollment (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrolled_at TIMESTAMP,
  course_id INT NOT NULL,
  user_id INT NOT NULL,
  CONSTRAINT uq_enrollment_user_course UNIQUE (user_id, course_id),
  CONSTRAINT fk_enrollment_course FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE,
  CONSTRAINT fk_enrollment_user FOREIGN KEY (user_id) REFERENCES user_(id) ON DELETE CASCADE
);
